config/routes.rb
Rails.application.routes.draw do
  resources :carts, only: [:show]
  resources :items, only: [:create, :update, :destroy]
  root 'bookstore#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :items

  include ActiveModel::Validations
  validates_with Tools::BookValidator
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :book
  belongs_to :cart

  include ActiveModel::Validations
  validates_with Tools::ItemValidator
end

app/models/tools/book_validator.rb
module Tools
  class BookValidator < ActiveModel::Validator
    def validate(book)
      %w(name description price).each do |attribute|
        next if book.send(attribute).present?

        book.errors.add :base, "#{attribute.humanize} can't be blank"
      end
    end
  end
end

app/models/tools/item_validator.rb
module Tools
  class ItemValidator < ActiveModel::Validator
    def validate(item)
      %w(quantity price).each do |attribute|
        next if item.send(attribute).to_i > 0

        item.errors.add :base, "#{attribute.humanize} must be greater than 0"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookstore_controller.rb
class BookstoreController < ApplicationController
  def index
    @books = Book.order(:name).limit(10)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = Cart.find(params[:id])
    @decorator_cart = CartDecorator.new(@cart)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    CartManager.add_item(book)
    redirect_to root_url
  end

  def update
    @cart = CartManager.cart
    @item = @cart.items.find(params[:id])
    @item.update_attributes(quantity: params[:quantity])
  end

  def destroy
    CartManager.remove_item(params[:id])
    respond_to do |format|
      format.html { redirect_to cart_url(CartManager.cart) }
      format.js { redirect_to cart_url(CartManager.cart) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookstore/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3>Bookstore</h3>
  </div>
</div>
<div class="row text-center">
  <% @books.each do |book| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <img src="http://placehold.it/200x150" alt="">
          <div class="caption">
            <h3><%= book.name %></h3>
            <p><%= truncate(book.description, length: 140) %></p>
            <p><%= number_to_currency(book.price) %></p>
            <p>
              <%= button_to 'Buy Now!', items_path(book_id: book), remote: true, class: "btn btn-primary" %>
            </p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/carts/show.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css"
      rel="stylesheet" type='text/css'>
<div class="container">
  <table id="cart" class="table table-hover table-condensed">
    <thead>
    <tr>
      <th style="width:50%">Product</th>
      <th style="width:10%">Price</th>
      <th style="width:8%">Quantity</th>
      <th style="width:22%" class="text-center">Subtotal</th>
      <th style="width:10%"></th>
    </tr>
    </thead>
    <tbody>
    <% @cart.items.each do |item| %>
        <tr>
          <td data-th="Product">
            <div class="row">
              <div class="col-sm-2 hidden-xs"><img src="http://placehold.it/100x100" alt="..." class="img-responsive"/>
              </div>
              <div class="col-sm-10">
                <h4 class="nomargin"><%= item.book.name %></h4>
                <p><%= item.book.description %></p>
              </div>
            </div>
          </td>
          <td class='price' data-th="Price"><%= number_to_currency(item.price) %></td>
          <td data-th="Quantity">
            <%= number_field_tag 'quantity', :quantity, min: 1, value: item.quantity,
                class: "form-control text-center quantity",  data: {path: item_path(item)} %>
          </td>
          <td data-th="Subtotal" class="text-center" id="subtotal_item_<%= item.id %>">
            <%= number_to_currency(ItemDecorator.new(item).total_price) %>
          </td>
          <td class="actions" data-th="">
            <%= link_to item, method: :delete, data: {confirm: 'Are you sure?'}, remote: true, class: "btn btn-danger btn-sm" do %>
                <i class="fa fa-trash-o"></i>
            <% end %></td>
          </td>
        </tr>
      </tbody>
    <% end %>
    <tfoot>
    <tr>
      <td><%= link_to '<i class="fa fa-angle-left"></i> Continue Shopping'.html_safe, root_url,
                      class: "btn btn-warning" %>
      </td>
      <td colspan="2" class="hidden-xs"></td>
      <td class="hidden-xs text-center">
        <strong id="subtotal">Total <%= number_to_currency(@decorator_cart.total_price) %></strong></td>
      <td><%= link_to root_url, class: "btn btn-success btn-block" do %>
            Checkout <i class="fa fa-angle-right"></i>
        <% end %></td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/items/destroy.js.erb
$("#cart_item_<%= item.id %>").remove();

app/views/items/update.js.erb
$("#subtotal_item_<%= @item.id %>").text("<%= number_to_currency(ItemDecorator.new(@item).total_price)%>");
$("#subtotal").text("<%= number_to_currency(CartDecorator.new(@cart).total_price) %>");

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to 'Books store', root_url %></li>
        <li class="nav-item"><%= link_to 'Cart', cart_path(CartManager.cart) %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container general">
      <%= yield %>
    </div>
  </body>
</html>